# Generated by Django 4.2.4 on 2023-08-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDBConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('prod', 'Production')], max_length=20)),
                ('host', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
